# add_new_gas_indices.R
# =========================================================================
# calculates new measures of pulmonary function and adds them to the large
# patient tibble as generated by import_data.R
#   - PF ratio
#   - Aa gradient
#   - CaO2 (total o2 in blood)
#
# =========================================================================
#
# * these measures are derived using the Liljestrand and Zander method for
# the estimation of CO from BP. It is not perfect!


# PF ratio


# Aa gradient


# CaO2


