# add_new_gas_indices.R
# =====================
# calculates new measures of pulmonary function and adds them to the large
# patient tibble as generated by import_data.R
#   - PF ratio
#   - Aa gradient
#   - total o2 in blood