# assemble_trimmed_dfs.R
# ========================================================
# this script cycles through the processed time-series .xlsx files for each
# patient (as generated by wrangle_from_metavision.R), isolates certain 
# parameters, and writes a new xlsx file for each patient. This new file
# will be used to assemble the final df to deploy logistic regression, etc. on

# STEPS:
# 1. select folder containing .xlsx files of interest
# 2. open each file and process it by isolating
#   a. GENERAL
#     - observation time (? time since admission better)
#     - patient position
#     - abg positioning
#   b. RESPIRATORY
#     - ABG values
#     - Ventilator values (fio2, MV, Paw, peak pressure, etco2, peep, peak flow)
#   c. CARDIOVASCULAR
#     - HR
#     - is on vasopressors
#   d. DEMOGRAPHICS
#     - age, height, weight (NB deal with height presence/absence)
#     - admission location
#     - outcome
#     - add a patient_id variable
# 3. write a new file, in a new folder