# assemble_trimmed_dfs.R
# ========================================================
# this script cycles through the processed time-series .xlsx files for each
# patient (as generated by wrangle_from_metavision.R), isolates certain 
# parameters, and writes a new xlsx file for each patient. This new file
# will be used to assemble the final df to deploy logistic regression, etc. on

library(tidyverse)
library(readxl)
library(writexl)
library(lubridate)

# get list of files
path <- '/Users/davidhannon/Documents/02. Medicine/Med_Programming/00. Patient DB/wrangled_outputs'
xlsx_list <- list.files(path = path, full.names = TRUE)
rm(path)

# get df of demographics
path <- '/Users/davidhannon/Documents/02. Medicine/Med_Programming/00. Patient DB/master_reference_lists/master_list_demographics.xlsx'
demographics <- read_xlsx(path = path)
rm(path)


# create list of desired variables
ideal_vars <- c('time',
                'patient_positioning',
                'patient_positioning_abg',
                'ph_abg',
                'pa_o2',
                'pa_co2',
                'bicarbonate_abg_a',
                'lactate_abg',
                'base_excess_vt',
                'potassium_abg',
                'sodium_abg',
                'ionised_calcium_abg',
                'anion_gap_abg',
                'glucose_abg',
                'total_haemoglobin',
                'fi_o2',
                'end_tidal_co2_marquette',
                'peep',
                'minute_volume_pb',
                'resp_rate',
                'set_tv_pb',
                'peak_inspiratory_pressure_measured_pb',
                'peak_inspiratory_pressure_measured_pb.x',
                'mean_airway_pressure_pb',
                'minute_volume_expired_s',
                'set_tidal_volume_servo',
                's_tidal_volume_inspired',
                'peak_inspiratory_pressure_measured_s',
                'mean_airway_pressure_s',
                'expired_minute_volume_measured_a',
                'peak_pressure_measured_a',
                'mean_airway_pressure_measured_a',
                'expired_tidal_volume_measured_avea',
                'minute_volume_d',
                'set_tv_d',
                'expiratory_tidal_volume_d',
                'peak_inspiratory_pressure_measured_d',
                'mean_airway_pressure_d',
                'plateau_airway_pressure_d',
                'resistance_d',
                'heart_rate',
                'arterial_pressure_systolic',
                'inotropic_vasoactive_agents_in_progress',
                'white_cell_count',
                'neutrophils',
                'lymphocytes',
                'c_reactive_protein',
                'urea',
                'pcre',
                'gfr',
                'haematocrit',
                'platelet_count',
                'albumin')


demo_vars <- c('patient_id',
               'gender',
               'age_years',
               'height_cm',
               'weight_kg',
               'los_days',
               'adm_location',
               'apache_ii')


patient_numbers <- tibble()


# create for loop
for (i in 1:length(xlsx_list)) {
  patient_id <- sub('.xlsx', '', basename(xlsx_list[i]))
  
  patient_details <- filter(demographics, patient_id == patient_id) %>% 
    select(patient_id,
           gender,
           age_years,
           height_cm,
           weight_kg,
           los_days,
           apache_ii,
           adm_location)
  
  patient_numbers <- xlsx_list[i] %>% read_xlsx(sheet = 'All_recorded') %>% 
    select(any_of(ideal_vars))
  
  patient_numbers$patient_id <- patient_details$patient_id[patient_details$patient_id == patient_id]
  patient_numbers$gender <- patient_details$gender[patient_details$patient_id == patient_id]
  patient_numbers$age_years <- patient_details$age_years[patient_details$patient_id == patient_id]
  patient_numbers$height_cm <- patient_details$height_cm[patient_details$patient_id == patient_id]
  patient_numbers$weight_kg <- patient_details$weight_kg[patient_details$patient_id == patient_id]
  patient_numbers$los_days <- patient_details$los_days[patient_details$patient_id == patient_id]
  patient_numbers$apache_ii <- patient_details$apache_ii[patient_details$patient_id == patient_id]
  patient_numbers$adm_location <- patient_details$adm_location[patient_details$patient_id == patient_id]
  
  # calculate new vars
  patient_numbers <- patient_numbers %>% 
    mutate(pf_ratio = pa_o2 / fi_o2,
           aa_gradient_pAco2 = ((fi_o2 * (101.3 - 6.3)) - (end_tidal_co2_marquette / 0.8)) - pa_o2,
           aa_gradient_paco2 = ((fi_o2 * (101.3 - 6.3)) - (pa_co2 / 0.8)) - pa_o2)
  
  # add 'time since admission' var
  patient_numbers <- patient_numbers %>% 
    mutate(time_since_adm_days = (as.numeric(time) - as.numeric(time[1])) / 86400)
  patient_numbers$time_since_adm_days <- round(patient_numbers$time_since_adm_days, 2)
  
  patient_numbers$prone_or_supine <- NA
  patient_numbers$proning_session <- NA
  
  patient_numbers <- patient_numbers %>% 
    relocate(patient_id) %>% 
    relocate(proning_session, .after = patient_id) %>% 
    relocate(prone_or_supine, .after = proning_session) %>% 
    relocate(time_since_adm_days, .after = prone_or_supine)
  
  patient_numbers <- bind_rows(patient_numbers, patient_numbers)
  
  # write the file
  path <- sprintf('/Users/davidhannon/Documents/02. Medicine/Med_Programming/00. Patient DB/ai_df/isolated_dfs/%s.xlsx', patient_id)
  write_xlsx(x = patient_numbers, path = path, format_headers = T)

}

# tidy up
rm(list = ls())
